// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLrvOQwtm5mE8gdYybGJi6ywBsQ_wbexI',
    appId: '1:283315088834:web:5a2486d992914fa8e0ba5b',
    messagingSenderId: '283315088834',
    projectId: 'bootstraps-38081',
    authDomain: 'bootstraps-38081.firebaseapp.com',
    storageBucket: 'bootstraps-38081.appspot.com',
    measurementId: 'G-JWNK4NPG8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUdS9AR-asjIV4W_vl7JjmjMIM7TzdsFw',
    appId: '1:283315088834:android:1e1f756ba2a2a089e0ba5b',
    messagingSenderId: '283315088834',
    projectId: 'bootstraps-38081',
    storageBucket: 'bootstraps-38081.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADo_1kz14mO053RcpkTqp0vlE2YYVBV5w',
    appId: '1:283315088834:ios:713401a6552295dce0ba5b',
    messagingSenderId: '283315088834',
    projectId: 'bootstraps-38081',
    storageBucket: 'bootstraps-38081.appspot.com',
    iosBundleId: 'com.example.flutterTodoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADo_1kz14mO053RcpkTqp0vlE2YYVBV5w',
    appId: '1:283315088834:ios:713401a6552295dce0ba5b',
    messagingSenderId: '283315088834',
    projectId: 'bootstraps-38081',
    storageBucket: 'bootstraps-38081.appspot.com',
    iosBundleId: 'com.example.flutterTodoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLrvOQwtm5mE8gdYybGJi6ywBsQ_wbexI',
    appId: '1:283315088834:web:facf7fb747991c0de0ba5b',
    messagingSenderId: '283315088834',
    projectId: 'bootstraps-38081',
    authDomain: 'bootstraps-38081.firebaseapp.com',
    storageBucket: 'bootstraps-38081.appspot.com',
    measurementId: 'G-019LC39VEV',
  );
}
